# -*- coding: utf-8 -*-
"""Hugging Face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mQnDOqczcuvH9-kCxiQQezKjWQcU2qo
"""

import numpy as np
import re
from transformers import pipeline
from IPython.display import Audio, display

def split_sentences(text):
    return re.split(r'(?<=[.!?])\s+', text.strip())

def tts_play_clean(text, model_name, pause_sec=0.4):
    tts = pipeline("text-to-speech", model=model_name)

    sentences = split_sentences(text)

    final_audio = []
    sr = None

    for sent in sentences:
        out = tts(sent)

        # FIX: force 1D audio
        audio = np.array(out["audio"], dtype=np.float32).flatten()
        sr = out["sampling_rate"]

        final_audio.append(audio)

        # silence pause
        pause = np.zeros(int(sr * pause_sec), dtype=np.float32)
        final_audio.append(pause)

    final_audio = np.concatenate(final_audio)

    # light normalization (no echo)
    final_audio /= np.max(np.abs(final_audio))

    display(Audio(final_audio, rate=sr))

translator = pipeline("translation", model="facebook/nllb-200-distilled-600M")

def translate(text):
    hi = translator(text, src_lang="eng_Latn", tgt_lang="hin_Deva")[0]["translation_text"]
    gu = translator(text, src_lang="eng_Latn", tgt_lang="guj_Gujr")[0]["translation_text"]
    return hi, gu

text = """
Hello, my name is Diaa.
I am an AI and Machine Learning enthusiast.
I enjoy building real world AI applications.
I am continuously learning new technologies.
"""

hi_text, gu_text = translate(text)

print("🔊 English (clean)")
tts_play_clean(text, "facebook/mms-tts-eng", pause_sec=0.45)

print("🔊 Hindi (clean)")
tts_play_clean(hi_text, "facebook/mms-tts-hin", pause_sec=0.5)

print("🔊 Gujarati (clean)")
tts_play_clean(gu_text, "facebook/mms-tts-guj", pause_sec=0.5)

